apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-$name
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /export/registry
    server: $nas
