apiVersion: v1
kind: PersistentVolume
metadata:
  name: PV_NAME_PLACEHOLDER
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: NFS_PATH_PLACEHOLDER
    server: NFS_SERVER_PLACEHOLDER
